In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.shape

(150, 5)

df.info()

# Missing Value Check

In [7]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

# Duplicate Row Check

In [8]:
df.duplicated().sum()

np.int64(3)

# Remove Duplicates

In [9]:
df = df.drop_duplicates()
df.shape

(147, 5)

# Standardize Format

In [10]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
df['species'] = df['species'].str.strip().str.lower()
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

# Final Summary

In [15]:
df.shape

(147, 5)

In [13]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
df.to_csv("cleaned_iris.csv", index=False)